version: '2'

services:
  server:
    build: server/
    ports:
      - 5000:80
    volumes:
      - ./config/:/var/www/html/config/
    depends_on:
      - redis

  worker:
    build: worker/
    volumes:
      - ./images/:/usr/app/images/
      - ./config/:/usr/app/src/config/
    depends_on:
      - nginx
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379

  nginx:
    image: nginx:1.15.1
    ports:
      - 4000:80
    volumes:
      - ./images/:/usr/share/nginx/html/
